# Generated by Django 5.0.6 on 2024-05-31 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Post_model',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
